# Generated by Django 3.1.7 on 2021-03-10 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RentalPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxlength', models.IntegerField()),
                ('description', models.CharField(max_length=350)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('rentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parktosleepAPI.rentee')),
            ],
        ),
        migrations.CreateModel(
            name='DaysAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parktosleepAPI.daysoftheweek')),
                ('rentalpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parktosleepAPI.rentalpost')),
            ],
        ),
        migrations.CreateModel(
            name='BookedSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rentalspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parktosleepAPI.rentalpost')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parktosleepAPI.rentee')),
            ],
        ),
    ]
