# Generated by Django 3.1.7 on 2021-03-10 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parktosleepAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daysavailable',
            old_name='rentalpost',
            new_name='rental_post',
        ),
        migrations.RenameField(
            model_name='rentalpost',
            old_name='endtime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='rentalpost',
            old_name='maxlength',
            new_name='max_length',
        ),
        migrations.RenameField(
            model_name='rentalpost',
            old_name='starttime',
            new_name='start_time',
        ),
    ]
