# Generated by Django 3.1.7 on 2021-03-10 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parktosleepAPI', '0002_auto_20210310_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedspot',
            old_name='rentalspot',
            new_name='rental_spot',
        ),
        migrations.RenameField(
            model_name='rentee',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='rentee',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
